import { redirect } from "next/navigation";
import { createClient } from "../../utils/supabase/server";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({ children }) {
  const supabase = await createClient();
  const { data, error } = await supabase.auth.getUser();

  if (data?.user?.email) {
    redirect("/");
  }
  if (error) {
    console.log(error);
  }

  return <>{children}</>;
}
